name: Deploy DotNet project to Azure Function App

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: 'rkocsignupvalidation'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'        # Update if your projects is in a subfolder
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Setup DotNet ${{ env.DOTNET_VERSION }}'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Publish Function App'
      run: |
        dotnet publish "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}" --configuration Release --output ./output

    - name: 'Deploy to Azure Function App'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: './output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
